"use client"

import { Fragment, useState } from "react";
import Modal from "@/components/Modal";
import { InformationCircleIcon, QuestionMarkCircleIcon } from '@heroicons/react/24/outline';
import { Amatic_SC } from 'next/font/google';

const amaticSC = Amatic_SC({
  weight: ['400', '700'],
  subsets: ['latin'],
  display: 'swap'
});

const Header = () => {
  const [howItWorks, setHowItWorks] = useState(false);
  const [info, setInfo] = useState(false);

  return (
    <Fragment>
      <header className="p-6 flex inline-flex-row w-full items-center" data-testid="layout">
        <button onClick={() => setInfo(state => !state)} style={{ height: 32 }}>
          <InformationCircleIcon className="size-8 text-black" />
        </button>
        <div className="flex-grow" />
        <h1 className={`font-bold text-7xl inline-block ${amaticSC.className}`} >Quirkle</h1>
        <div className="flex-grow" />
        <button onClick={() => setHowItWorks(state => !state)} style={{ height: 32 }}>
          <QuestionMarkCircleIcon className="size-8 text-black" />
        </button>
      </header>

      <Modal
        title="How to Play"
        isOpen={howItWorks}
        close={() => setHowItWorks(state => !state)}
        height={350}
      >
        <div>
          <div>👤 Given the names of 4 individuals, 3 of them share a connection and the other is an outlier.</div>
          <div className="mt-6">🌟 Select the one you believe to be the <strong>outlier</strong> and click submit</div>
          <div className="mt-6">🔍 <i>Stuck?</i> Click <strong>"Give Clue"</strong> to recieve up to 4 clues to aid you in your search.</div>
        </div>
      </Modal>

      <Modal
        title="Information"
        isOpen={info}
        close={() => setInfo(state => !state)}
        height={550}
      >
        <div>
          <div>🤖 Quirkle is a daily puzzle generated by AI.</div>
          <div className="mt-6">The aim of the puzzle is to identify the outlier from 4 given individuals</div>
          <div className="mt-6">The game uses OpenAI GPT 4 to generate a new round each day at midnight (GMT)</div>
          <div className="mt-6">🌟 <strong><u>Tip</u></strong></div>
          <div className="mt-2">Because this is AI generated, the puzzle may not be perfect.</div>
          <div className="mt-4">The connection tends towards something significant, such as a body of work or field of expertise</div>
          <div className="mt-4">The connection is less likely to be a generic connection such as "3 of them have brown hair"</div>
        </div>
      </Modal>
    </Fragment>
  );
};

export default Header;